#!/bin/bash

git clone ../../../kanapi kanapi
#docker build -t kanapi-cli:ci .
if [ ! -d ${HOME}/src-ci ] ; then mkdir ${HOME}/src-ci ; fi

docker run -t -v ${DIR}/kanapi:/kanapi_build/kanapi -v ${HOME}/src-ci:/kanapi_0.9/x86_64/home/src-ci \
	-v ${HOME}/.ccache:/kanapi_0.9/x86_64/home/.ccache -e HOME=/kanapi_0.9/x86_64/home kanapi/kanapi-bbs \
	bash -c "ccache -s; /kanapi_build/kanapi/kanapi_system/docker/configure; cd /kanapi_build/kanapi/kanapi_system/x86_64 && ./install gzip verbose"

docker run -t -v ${DIR}/kanapi:/kanapi_build/kanapi -v ${HOME}/src-ci:/kanapi_0.9/x86_64/home/src-ci \
	-v ${HOME}/.ccache:/kanapi_0.9/x86_64/home/.ccache -e HOME=/kanapi_0.9/x86_64/home kanapi/kanapi-bbs \
	bash -c "ccache -s"

