all:
	ccache -s
	df -h
	set

cli-docker:
	cd cli ; ./build

rm-test:
	cd sbs ; ./build

all_chroot: bbs_sbs t_compression t_system

bbs_sbs:
	chroot ../sbs-`uname -m` /_start_bbs_build

t_compression:
	bash -c "export PKG_COMMAND=t_compression; chroot ../sbs-`uname -m` /_start_install"

t_system:
	bash -c "export PKG_COMMAND=t_system; chroot ../sbs-`uname -m` /_start_install"

core_cli:
	bash -c "export PKG_COMMAND=cli; chroot ../sbs-`uname -m` /_start_install"

bbs: base
	cd ../kanapi_system/`uname -m`   ; make bbs	 ACTION=install V=1

check_links:
	./prepare_links

base: check_links
	cd ../kanapi_system/`uname -m`   ; make gettext ACTION=install
	cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install

test:
	echo "tests disabled"

busybox:	
	cd ../kanapi_system/`uname -m`   ; make busybox	 ACTION=install V=1

ncurses5: check_links
	cd ../kanapi_system/`uname -m`   ; make ncurses5 ACTION=install V=1

perl: check_links
	cd ../kanapi_system/`uname -m`   ; make file ACTION=install V=1
	cd ../kanapi_system/`uname -m`   ; make perl ACTION=install V=1


